Repository Peachy-Peachy/Taskify, pull requests merged in 2023-12, with the labels that each got.

#64 [Feat] modal input component 구현
  package-lock.json
  package.json
  public/svgs/icon-greater.svg
  public/svgs/icon-less.svg
  public/svgs/index.ts
  src/components/chips/TagChip.tsx
  src/components/inputs/Input.tsx
  src/components/inputs/Textarea.tsx
  src/styles/globals.css
Labels: feat

#71 [refector] ImageDrop 컴포넌트 수정
  src/components/image-drop/ImageDrop.tsx
  src/components/modal-logo/ModalLogo.tsx
Labels: refactor

#78 [Feat] mypage 구현
  src/components/image-drop/ImageDrop.tsx
  src/containers/MyPage/components/PasswordManageBox.tsx
  src/containers/MyPage/components/ProfileManageBox.tsx
  src/containers/MyPage/index.tsx
  src/pages/mypage.tsx
  src/styles/globals.css
Labels: feat

#81 [feat] signin page
  src/components/inputs/AuthInput.tsx
  src/containers/Auth/SigninContainer.tsx
  src/containers/Auth/validation.ts
  src/pages/signin.tsx
Labels: feat

#88 [feat] ImageUrl atom 구현
  src/components/image-drop/ImageDrop.tsx
  src/store/imageUrlAtom.ts
Labels: feat

#95 [feat] modal component
  src/components/buttons/PrimaryButton.tsx
  src/components/buttons/SecondaryButton.tsx
  src/components/dropdowns/ManagerDropdown.tsx
  src/components/dropdowns/StateDropdown.tsx
  src/components/inputs/Input.tsx
  src/components/inputs/InputComponents/DateInput.tsx
  src/components/inputs/InputComponents/TagInput.tsx
  src/components/inputs/InputComponents/TextInput.tsx
  src/components/inputs/InputComponents/Textarea.tsx
  src/components/inputs/InputComponents/index.ts
  src/components/inputs/Textarea.tsx
  src/components/modal/Confirm.tsx
  src/components/modal/ConfirmComponents/CheckConfirm.tsx
  src/components/modal/ConfirmComponents/DeleteConfirm.tsx
  src/components/modal/ConfirmComponents/index.ts
  src/components/modal/Form.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/components/modal/FormComponents/TodoForm.tsx
  src/components/modal/FormComponents/index.ts
  src/components/modal/Modal.tsx
  src/styles/globals.css
Labels: feat

#90 [feat] signUp page
  src/components/inputs/AuthInput.tsx
  src/components/inputs/authPlaceholder.ts
  src/containers/Auth/SignUpContainer.tsx
  src/containers/Auth/validation.ts
  src/pages/signUp.tsx
Labels: feat

#101 [fix] signIn page
  src/containers/Auth/SigninContainer.tsx
  src/pages/signin.tsx
Labels: fix

#107 [fix] Modal의 Form Components 리턴문 수정
  src/components/modal/Form.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/components/modal/FormComponents/TodoForm.tsx
Labels: fix

#115 [fix] signUp page
  src/containers/Auth/SignUpContainer.tsx
Labels: fix

#109 [feat] myDashboard page columns 생성/수정 기능
  src/components/inputs/Input.tsx
  src/components/inputs/InputComponents/TextInput.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/containers/MyDashboard/[id]/components/DashboardColumn.tsx
  src/containers/MyDashboard/[id]/index.tsx
  src/store/columnsAtom.ts
Labels: feat

#111 [feat] 대시보드 수정 기능 구현
  src/containers/MyDashboard/edit.tsx
  src/pages/mydashboard/[dashboardId]/edit.tsx
  src/pages/mydashboard/[dashboardId]/index.tsx
Labels: feat

#117 [feat] dashboard page 컬럼 삭제 기능
  src/components/modal/Confirm.tsx
  src/components/modal/ConfirmComponents/DeleteConfirm.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/containers/MyDashboard/[id]/components/DashboardColumn.tsx
Labels: feat

#132 [fix] Layout 수정
  src/components/Header.tsx
  src/components/Layout.tsx
  src/containers/Dashboard/DashboardId.tsx
  src/containers/Landing/index.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: fix

#134 [fix] signup page
  src/containers/Auth/SignUpContainer.tsx
Labels: fix

#136 [fix] Table 컴포넌트 api 연결 및 edit 페이지에 적용
  src/components/Members.tsx
  src/components/tables/DashboardInfoTable.tsx
  src/components/tables/index.tsx
  src/containers/Dashboard/Edit.tsx
  src/pages/api/mock.ts
Labels: fix

#137 [feat] modal 컴포넌트 InviteForm 제작 및 edit 페이지에 연결
  src/components/InputContainer.tsx
  src/components/modal/Form.tsx
  src/components/modal/FormComponents/InviteForm.tsx
  src/components/modal/FormComponents/index.ts
  src/components/tables/DashboardInfoTable.tsx
  src/containers/Dashboard/Edit.tsx
  src/containers/MyPage/components/PasswordManageBox.tsx
  src/containers/MyPage/components/ProfileManageBox.tsx
Labels: feat

#152 [fix] dashboard api 연결
  src/components/DashboardColorDot.tsx
  src/components/SideMenu.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/components/tables/InvitedDashboardsTable.tsx
  src/components/tables/index.tsx
  src/containers/Dashboard/Edit.tsx
  src/containers/Dashboard/components/ArrowButtonPageChange.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/containers/Dashboard/components/MyDashboardButton.tsx
  src/containers/Dashboard/components/MyDashboardButtons.tsx
  src/containers/Dashboard/index.tsx
  src/hooks/searchInvitedDashboards.ts
  src/pages/api/mock.ts
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: fix

#154 [fix] 색깔 선택 함수 간략화
  src/utils/generateColor.ts
Labels: fix

#153 [feat] 공통 Layout 구현
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/Members.tsx
  src/components/SideMenu.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/Layout.tsx
  src/components/layouts/SideMenu.tsx
  src/components/layouts/headers/DashboardHeader.tsx
  src/components/layouts/headers/LandingHeader.tsx
  src/components/logos/Logo.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/components/modal/FormComponents/InviteForm.tsx
  src/components/tables/DashboardInfoTable.tsx
  src/containers/Landing/index.tsx
  src/pages/_app.tsx
  src/pages/api/mock.ts
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/dashboard/index.tsx
  src/pages/mypage.tsx
  tailwind.config.ts
Labels: feat

#155 [fix] input container 에러 메시지 구현
  src/components/inputs/InputContainer.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/components/modal/FormComponents/InviteForm.tsx
  src/containers/Auth/validation.ts
  src/containers/MyPage/components/PasswordManageBox.tsx
  src/containers/MyPage/components/ProfileManageBox.tsx
  src/containers/MyPage/index.tsx
Labels: fix
