Repository Peachy-Peachy/Taskify, pull requests merged in 2024-01, with the labels that each got.

#157 [fix] modal component
  src/components/modal/Confirm.tsx
  src/components/modal/ConfirmComponents/DeleteConfirm.tsx
  src/components/modal/Form.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/components/modal/Modal.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/store/modalAtom.ts
Labels: fix

#158 [feat] dashboardId 페이지 더보기, 무한스크롤 기능 추가
  src/components/layouts/Layout.tsx
  src/components/layouts/SideMenu.tsx
  src/components/layouts/headers/DashboardHeader.tsx
  src/components/layouts/headers/LandingHeader.tsx
  src/containers/Dashboard/DashboardId.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/hooks/useInfiniteScroll.ts
Labels: feat

#163 [feat] card 상세보기 모달 & 중복 모달 해결
  src/components/Card.tsx
  src/components/comment/Comments.tsx
  src/components/comment/formatDate.ts
  src/components/icons/Close.tsx
  src/components/icons/Kebab.tsx
  src/components/inputs/InputComponents/Textarea.tsx
  src/components/layouts/Layout.tsx
  src/components/modal/Form.tsx
  src/components/modal/FormComponents/CardViewDetail.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/components/modal/FormComponents/index.ts
  src/components/modal/Modal.tsx
  src/components/tables/DashboardInfoTable.tsx
  src/containers/Dashboard/DashboardId.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/containers/Dashboard/components/MyDashboardButtons.tsx
  src/pages/api/mock.ts
  src/store/commentAtom.ts
  src/store/modalAtom.ts
  src/styles/globals.css
Labels: feat

#167 [chore] useInfiniteScroll훅 및 dashboardId 페이지 세부 코드 수정
  src/components/layouts/Layout.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/hooks/useInfiniteScroll.ts
Labels: fix

#169 [fix] 사이드 메뉴 대시보드 리스트 동기화
  src/components/layouts/SideMenu.tsx
  src/components/layouts/headers/DashboardHeader.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/store/dashboardUpdateAtom.tsx
Labels: fix

#170 [feat] 사이드 메뉴 무한 스크롤 및 스켈레톤 UI 구현
  package-lock.json
  package.json
  src/components/layouts/SideMenu.tsx
  src/components/skeletons/DeferredSuspense.tsx
  src/components/skeletons/SideMenuSkeleton.tsx
  src/pages/_app.tsx
Labels: feat

#171 [feat] 대시보드 삭제하기 기능 구현
  src/containers/Dashboard/Edit.tsx
Labels: feat

#174 [feat] 비밀번호 변경 에러 메시지 추가 및 토글 버튼 구현
  src/components/inputs/InputContainer.tsx
  src/components/layouts/headers/DashboardHeader.tsx
  src/containers/Auth/validation.ts
  src/containers/MyPage/components/PasswordManageBox.tsx
Labels: feat

#176 [feat] dashboardId dnd 구현
  next.config.js
  package-lock.json
  package.json
  src/components/Card.tsx
  src/containers/Dashboard/DashboardId.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/containers/Dashboard/components/MyDashboardButtons.tsx
  src/hooks/useInfiniteScroll.ts
Labels: feat

#181 [fix] 대시보드 title 글자 수 표시 제한
  src/components/layouts/SideMenu.tsx
  src/containers/Dashboard/components/MyDashboardButton.tsx
  src/utils/reduceText.ts
Labels: fix

#179 [fix] 각 페이지 헤더 타이틀 태그 추가
  package-lock.json
  src/components/Card.tsx
  src/containers/Dashboard/DashboardId.tsx
  src/containers/Dashboard/components/MyDashboardButtons.tsx
  src/pages/_document.tsx
  src/pages/dashboard/[dashboardId]/edit.tsx
  src/pages/dashboard/[dashboardId]/index.tsx
  src/pages/dashboard/index.tsx
  src/pages/mypage.tsx
  src/store/infiniteScrollAtom.ts
Labels: fix

#185 [chore] 대시보드 edit 페이지 title 글자 수 표시 제한
  src/containers/Dashboard/Edit.tsx
  src/pages/_document.tsx
Labels: chore

#189 [feat] 카드 삭제 기능 구현
  src/components/modal/FormComponents/CardViewDetail.tsx
  src/containers/Dashboard/DashboardId.tsx
Labels: feat

#190 [chore] 다크모드 색상 변경, 커스텀 스크롤바 적용
  src/components/Members.tsx
  src/components/buttons/Facebook.tsx
  src/components/buttons/Instagram.tsx
  src/components/buttons/PrimaryButton.tsx
  src/components/buttons/SecondaryButton.tsx
  src/components/layouts/Layout.tsx
  src/components/layouts/SideMenu.tsx
  src/containers/Dashboard/DashboardId.tsx
Labels: chore

#192 [chore] 대시보드 생성 모달 타이틀 인풋 required role 추가 / types 폴더 구조 변경
  src/components/Card.tsx
  src/components/Members.tsx
  src/components/inputs/InputComponents/TextInput.tsx
  src/components/inputs/InputComponents/Textarea.tsx
  src/components/layouts/Footer.tsx
  src/components/layouts/SideMenu.tsx
  src/components/layouts/headers/DashboardHeader.tsx
  src/components/modal/FormComponents/CardViewDetail.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/components/modal/FormComponents/InviteForm.tsx
  src/components/tables/DashboardInfoTable.tsx
  src/components/tables/InvitedDashboardsTable.tsx
  src/components/tables/index.tsx
  src/containers/Dashboard/DashboardId.tsx
  src/containers/Dashboard/Edit.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/containers/Dashboard/components/MyDashboardButton.tsx
  src/containers/Dashboard/components/MyDashboardButtons.tsx
  src/hooks/useSearchInvitedDashboards.ts
  src/types.ts
Labels: chore

#194 [feat] card 수정기능 생성
  src/components/comment/Comments.tsx
  src/components/dropdowns/ManagerDropdown.tsx
  src/components/dropdowns/StateDropdown.tsx
  src/components/image-drop/ImageDrop.tsx
  src/components/inputs/Input.tsx
  src/components/inputs/InputComponents/DateInput.tsx
  src/components/modal/FormComponents/CardViewDetail.tsx
  src/components/modal/FormComponents/TodoForm.tsx
  src/components/modal/Modal.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/store/cardAtom.ts
  src/store/createCardAtom.ts
  src/utils/dateFormat.ts
Labels: feat

#200 [fix] modal
  src/components/dropdowns/ManagerDropdown.tsx
  src/components/dropdowns/StateDropdown.tsx
  src/components/inputs/InputComponents/TextInput.tsx
  src/components/modal/Confirm.tsx
  src/components/modal/ConfirmComponents/CheckConfirm.tsx
  src/components/modal/ConfirmComponents/DeleteConfirm.tsx
  src/components/modal/Form.tsx
  src/components/modal/FormComponents/CardViewDetail.tsx
  src/components/modal/FormComponents/ColumnForm.tsx
  src/components/modal/FormComponents/DashboardForm.tsx
  src/components/modal/FormComponents/InviteForm.tsx
  src/components/modal/FormComponents/TodoForm.tsx
  src/components/modal/Modal.tsx
  src/components/tables/InvitedDashboardsTable.tsx
  src/containers/Auth/SignInContainer.tsx
  src/containers/Dashboard/components/DashboardColumn.tsx
  src/containers/Dashboard/components/MyDashboardButtons.tsx
  src/containers/Dashboard/index.tsx
  src/containers/MyPage/components/ProfileManageBox.tsx
  src/hooks/useSearchInvitedDashboards.ts
  src/pages/dashboard/[dashboardId]/index.tsx
Labels: fix

#203 [fix] 두 번째 할 일 이미지 없이 생성 시 생성되지 않는 현상
  src/components/modal/FormComponents/TodoForm.tsx
Labels: fix
